//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MONSTER                     157
#define IDB_TESTAJ                      160
#define IDB_BLUE                        163
#define IDB_BITMAP3                     164
#define IDB_RED                         164
#define IDB_LOGOCANDY1                  165
#define IDB_LOGOCANDY2                  166
#define IDB_LOGOCANDY3                  167
#define IDB_LOGOCANDY4                  168
#define IDB_LOGOCANDY5                  169
#define IDB_LOGOCANDY6                  170
#define IDB_LOGOCANDY7                  171
#define IDB_LOGOCANDY8                  172
#define IDB_LOGOCANDY9                  173
#define IDB_LOGOCANDY10                 174
#define IDB_LOGOCANDY11                 175
#define IDB_LOGOCANDY12                 176
#define IDB_LOGOCANDY13                 177
#define IDB_LOGOCANDY14                 178
#define IDB_LOGOCANDY15                 179
#define IDB_LOGOCANDY16                 180
#define IDB_LOGOCANDY17                 181
#define IDB_LOGOCANDY18                 182
#define IDB_LOGOCANDY19                 183
#define IDB_LOGOCANDY20                 184
#define IDB_LOGOCANDY21                 185
#define IDB_LOGOCANDY22                 186
#define IDB_LOGOCANDY23                 187
#define IDB_LOGOTIFFY0                  189
#define IDB_LOGOTIFFY1                  190
#define IDB_LOGOTIFFY2                  191
#define IDB_LOGOTIFFY3                  192
#define IDB_LOGOTIFFY4                  193
#define IDB_LOGOTIFFY5                  194
#define IDB_LOGOTIFFY6                  195
#define IDB_LOGOTIFFY7                  196
#define IDB_LOGOTIFFY8                  197
#define IDB_LOGOTIFFY9                  198
#define IDB_LOGOTOFFEE46                199
#define IDB_LOGOTOFFEE1                 199
#define IDB_LOGOTOFFEE2                 200
#define IDB_LOGOTOFFEE3                 201
#define IDB_LOGOTOFFEE4                 202
#define IDB_LOGOTOFFEE5                 203
#define IDB_LOGOTOFFEE6                 204
#define IDB_PLAYBUTTON_1                206
#define IDB_PLAYBUTTON_2                209
#define IDB_PLAYBUTTON_3                210
#define IDB_PLAYBUTTON_4                211
#define IDB_PLAYBUTTON_5                212
#define IDB_PLAYBUTTON_6                213
#define IDB_PLAYBUTTON_7                214
#define IDB_PLAYBUTTON_8                215
#define IDB_PLAYBUTTON_9                216
#define IDB_PLAYBUTTON_10               217
#define IDB_PLAYBUTTON_11               218
#define IDB_PLAYBUTTON_12               219
#define IDB_BITMAP4                     221
#define IDB_BITMAP5                     223
#define IDB_STAGE_BUTTON_BLUE           224
#define IDB_ORANGE_C                    226
#define IDB_STAGE_BUTTON_GREEN          226
#define IDB_PURPLE_C                    227
#define IDB_STAGE_BUTTON_GREY           227
#define IDB_STAGE_BUTTON_RED            228
#define IDB_BITMAP6                     229
#define IDB_YELLOW_C                    229
#define IDB_STAGE_BUTTON_YELLOW         229
#define IDB_SUPER                       232
#define IDB_SUPER_C                     234
#define IDB_BLUE_C                      236
#define IDB_RED_C                       237
#define IDB_GREEN_C                     239
#define IDB_BLUE_CLICKED                240
#define IDB_GREEN_CLICKED               241
#define IDB_ORANGE_CLICKED              242
#define IDB_PURPLE_CLICKED              244
#define IDB_RED_CLICKED                 245
#define IDB_YELLOW_CLICKED              246
#define IDB_BLUE_HOR                    247
#define IDB_GREEN_HOR                   248
#define IDB_ORANGE_HOR                  249
#define IDB_PURPLE_HOR                  250
#define IDB_RED_HOR                     252
#define IDB_YELLOW_HOR                  253
#define IDB_BLUE_HOR_C                  254
#define IDB_GREEN_HOR_C                 255
#define IDB_ORANGE_HOR_C                256
#define IDB_PURPLE_HOR_C                257
#define IDB_RED_HOR_C                   259
#define IDB_YELLOW_HOR_C                260
#define IDB_BLUE_VER                    261
#define IDB_GREEN_VER                   262
#define IDB_ORANGE_VER                  263
#define IDB_PURPLE_VER                  264
#define IDB_RED_VER                     265
#define IDB_YELLOW_VER                  266
#define IDB_BLUE_VER_C                  267
#define IDB_GREEN_VER_C                 268
#define IDB_ORANGE_VER_C                269
#define IDB_PURPLE_VER_C                271
#define IDB_RED_VER_C                   272
#define IDB_YELLOW_VER_C                273
#define IDB_ORANGE_PACK                 278
#define IDB_BLUE_PACK                   279
#define IDB_GREEN_PACK                  280
#define IDB_PURPLE_PACK                 281
#define IDB_RED_PACK                    282
#define IDB_YELLOW_PACK                 283
#define IDB_BLUE_PACK_C                 284
#define IDB_GREEN_PACK_C                285
#define IDB_ORANGE_PACK__C              286
#define IDB_ORANGE_PACK_C               286
#define IDB_PURPLE_PACK_C               287
#define IDB_RED_PACK_C                  288
#define IDB_YELLOW_PACK_C               289
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        290
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
