//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MONSTER                     157
#define IDB_BLUE                        163
#define IDB_BITMAP3                     164
#define IDB_RED                         164
#define IDB_LOGOCANDY1                  165
#define IDB_LOGOCANDY2                  166
#define IDB_LOGOCANDY3                  167
#define IDB_LOGOCANDY4                  168
#define IDB_LOGOCANDY5                  169
#define IDB_LOGOCANDY6                  170
#define IDB_LOGOCANDY7                  171
#define IDB_LOGOCANDY8                  172
#define IDB_LOGOCANDY9                  173
#define IDB_LOGOCANDY10                 174
#define IDB_LOGOCANDY11                 175
#define IDB_LOGOCANDY12                 176
#define IDB_LOGOCANDY13                 177
#define IDB_LOGOCANDY14                 178
#define IDB_LOGOCANDY15                 179
#define IDB_LOGOCANDY16                 180
#define IDB_LOGOCANDY17                 181
#define IDB_LOGOCANDY18                 182
#define IDB_LOGOCANDY19                 183
#define IDB_LOGOCANDY20                 184
#define IDB_LOGOCANDY21                 185
#define IDB_LOGOCANDY22                 186
#define IDB_LOGOCANDY23                 187
#define IDB_LOGOTIFFY0                  189
#define IDB_LOGOTIFFY1                  190
#define IDB_LOGOTIFFY2                  191
#define IDB_LOGOTIFFY3                  192
#define IDB_LOGOTIFFY4                  193
#define IDB_LOGOTIFFY5                  194
#define IDB_LOGOTIFFY6                  195
#define IDB_LOGOTIFFY7                  196
#define IDB_LOGOTIFFY8                  197
#define IDB_LOGOTIFFY9                  198
#define IDB_LOGOTOFFEE46                199
#define IDB_LOGOTOFFEE1                 199
#define IDB_LOGOTOFFEE2                 200
#define IDB_LOGOTOFFEE3                 201
#define IDB_LOGOTOFFEE4                 202
#define IDB_LOGOTOFFEE5                 203
#define IDB_LOGOTOFFEE6                 204
#define IDB_PLAYBUTTON_1                206
#define IDB_PLAYBUTTON_2                209
#define IDB_PLAYBUTTON_3                210
#define IDB_PLAYBUTTON_4                211
#define IDB_PLAYBUTTON_5                212
#define IDB_PLAYBUTTON_6                213
#define IDB_PLAYBUTTON_7                214
#define IDB_PLAYBUTTON_8                215
#define IDB_PLAYBUTTON_9                216
#define IDB_PLAYBUTTON_10               217
#define IDB_PLAYBUTTON_11               218
#define IDB_PLAYBUTTON_12               219
#define IDB_BITMAP4                     221
#define IDB_BITMAP5                     223
#define IDB_STAGE_BUTTON_BLUE           224
#define IDB_ORANGE_C                    226
#define IDB_STAGE_BUTTON_GREEN          226
#define IDB_PURPLE_C                    227
#define IDB_STAGE_BUTTON_GREY           227
#define IDB_STAGE_BUTTON_RED            228
#define IDB_BITMAP6                     229
#define IDB_YELLOW_C                    229
#define IDB_STAGE_BUTTON_YELLOW         229
#define IDB_SUPER                       232
#define IDB_SUPER_C                     234
#define IDB_BLUE_C                      236
#define IDB_RED_C                       237
#define IDB_GREEN_C                     239
#define IDB_BLUE_CLICKED                240
#define IDB_GREEN_CLICKED               241
#define IDB_ORANGE_CLICKED              242
#define IDB_PURPLE_CLICKED              244
#define IDB_RED_CLICKED                 245
#define IDB_YELLOW_CLICKED              246
#define IDB_BLUE_HOR                    247
#define IDB_GREEN_HOR                   248
#define IDB_ORANGE_HOR                  249
#define IDB_PURPLE_HOR                  250
#define IDB_RED_HOR                     252
#define IDB_YELLOW_HOR                  253
#define IDB_BLUE_HOR_C                  254
#define IDB_GREEN_HOR_C                 255
#define IDB_ORANGE_HOR_C                256
#define IDB_PURPLE_HOR_C                257
#define IDB_RED_HOR_C                   259
#define IDB_YELLOW_HOR_C                260
#define IDB_BLUE_VER                    261
#define IDB_GREEN_VER                   262
#define IDB_ORANGE_VER                  263
#define IDB_PURPLE_VER                  264
#define IDB_RED_VER                     265
#define IDB_YELLOW_VER                  266
#define IDB_BLUE_VER_C                  267
#define IDB_GREEN_VER_C                 268
#define IDB_ORANGE_VER_C                269
#define IDB_PURPLE_VER_C                271
#define IDB_RED_VER_C                   272
#define IDB_YELLOW_VER_C                273
#define IDB_ORANGE_PACK                 278
#define IDB_BLUE_PACK                   279
#define IDB_GREEN_PACK                  280
#define IDB_PURPLE_PACK                 281
#define IDB_RED_PACK                    282
#define IDB_YELLOW_PACK                 283
#define IDB_BLUE_PACK_C                 284
#define IDB_GREEN_PACK_C                285
#define IDB_ORANGE_PACK__C              286
#define IDB_ORANGE_PACK_C               286
#define IDB_PURPLE_PACK_C               287
#define IDB_RED_PACK_C                  288
#define IDB_YELLOW_PACK_C               289
#define IDB_BLACKBAR                    290
#define IDB_0                           293
#define IDB_1                           295
#define IDB_2                           296
#define IDB_3                           335
#define IDB_4                           336
#define IDB_5                           337
#define IDB_8                           343
#define IDB_9                           345
#define IDB1_0                          346
#define IDB1_1                          347
#define IDB1_2                          348
#define IDB1_3                          349
#define IDB1_4                          350
#define IDB1_5                          351
#define IDB1_6                          352
#define IDB1_7                          354
#define IDB1_8                          355
#define IDB1_9                          357
#define IDB2_0                          358
#define IDB2_1                          359
#define IDB2_2                          360
#define IDB2_3                          361
#define IDB2_4                          362
#define IDB2_5                          363
#define IDB2_6                          364
#define IDB2_7                          365
#define IDB2_8                          366
#define IDB2_9                          368
#define IDB3_0                          369
#define IDB3_1                          370
#define IDB3_2                          371
#define IDB3_3                          372
#define IDB3_4                          373
#define IDB3_5                          374
#define IDB3_6                          375
#define IDB3_7                          376
#define IDB3_8                          377
#define IDB_BITMAP7                     378
#define IDB3_9                          378
#define IDB_CONTAINER                   381
#define IDB_INGAME_LOADING              382
#define IDB_6                           385
#define IDB_7                           386
#define IDB_NEXTBTN_0                   387
#define IDB_NEXTBTN_1                   388
#define IDB_NEXTBTN_2                   389
#define IDB_NEXTBTN_3                   390
#define IDB_NEXTBTN_4                   391
#define IDB_NEXTBTN_5                   392
#define IDB_NEXTBTN_6                   393
#define IDB_NEXTBTN_7                   395
#define IDB_NEXTBTN_8                   396
#define IDB_NEXTBTN_9                   397
#define IDB_RETRYBTN_0                  398
#define IDB_RETRYBTN_1                  399
#define IDB_RETRYBTN_2                  400
#define IDB_RETRYBTN_3                  401
#define IDB_RETRYBTN_4                  403
#define IDB_RETRYBTN_5                  404
#define IDB_RETRYBTN_6                  405
#define IDB_RETRYBTN_7                  407
#define IDB_RETRYBTN_8                  409
#define IDB_BITMAP8                     410
#define IDB_RETRYBTN_9                  410
#define IDB_BLUE_EXPL1                  411
#define IDB_BLUE_EXPL2                  413
#define IDB_BLUE_EXPL3                  414
#define IDB_BLUE_EXPL4                  415
#define IDB_BLUE_EXPL5                  417
#define IDB_BLUE_EXPL6                  418
#define IDB_BLUE_EXPL7                  419
#define IDB_BLUE_EXPL8                  420
#define IDB_BLUE_EXPL9                  421
#define IDB_BLUE_EXPL10                 422
#define IDB_GREEN_EXPL1                 559
#define IDB_GREEN_EXPL2                 560
#define IDB_GREEN_EXPL3                 561
#define IDB_GREEN_EXPL4                 562
#define IDB_GREEN_EXPL5                 563
#define IDB_GREEN_EXPL6                 564
#define IDB_GREEN_EXPL7                 565
#define IDB_GREEN_EXPL8                 566
#define IDB_GREEN_EXPL9                 567
#define IDB_GREEN_EXPL10                568
#define IDB_ORANGE_EXPL1                569
#define IDB_ORANGE_EXPL2                570
#define IDB_ORANGE_EXPL3                571
#define IDB_ORANGE_EXPL4                572
#define IDB_ORANGE_EXPL5                573
#define IDB_ORANGE_EXPL6                574
#define IDB_ORANGE_EXPL7                575
#define IDB_ORANGE_EXPL8                576
#define IDB_ORANGE_EXPL9                577
#define IDB_ORANGE_EXPL10               578
#define IDB_PURPLE_EXPL1                579
#define IDB_PURPLE_EXPL2                580
#define IDB_PURPLE_EXPL3                581
#define IDB_PURPLE_EXPL4                582
#define IDB_PURPLE_EXPL5                583
#define IDB_PURPLE_EXPL6                584
#define IDB_PURPLE_EXPL7                585
#define IDB_PURPLE_EXPL8                586
#define IDB_PURPLE_EXPL9                587
#define IDB_PURPLE_EXPL10               588
#define IDB_RED_EXPL1                   589
#define IDB_RED_EXPL2                   590
#define IDB_RED_EXPL3                   591
#define IDB_RED_EXPL4                   592
#define IDB_RED_EXPL5                   593
#define IDB_RED_EXPL6                   594
#define IDB_RED_EXPL7                   595
#define IDB_RED_EXPL8                   596
#define IDB_RED_EXPL9                   597
#define IDB_RED_EXPL10                  598
#define IDB_YELLOW_EXPL1                599
#define IDB_YELLOW_EXPL2                600
#define IDB_YELLOW_EXPL3                601
#define IDB_YELLOW_EXPL4                602
#define IDB_YELLOW_EXPL5                603
#define IDB_YELLOW_EXPL6                604
#define IDB_YELLOW_EXPL7                605
#define IDB_YELLOW_EXPL8                606
#define IDB_YELLOW_EXPL9                607
#define IDB_YELLOW_EXPL10               608
#define IDB_BITMAP9                     609
#define IDB_BLUE_H_EXPL1                609
#define IDB_BLUE_H_EXPL2                610
#define IDB_BLUE_H_EXPL3                611
#define IDB_BLUE_H_EXPL4                612
#define IDB_BLUE_H_EXPL5                613
#define IDB_BLUE_H_EXPL6                614
#define IDB_BLUE_H_EXPL7                615
#define IDB_BLUE_H_EXPL8                616
#define IDB_BLUE_H_EXPL9                617
#define IDB_BLUE_H_EXPL10               618
#define IDB_BLUE_H_EXPL11               619
#define IDB_BLUE_H_EXPL12               620
#define IDB_BLUE_H_EXPL13               621
#define IDB_BLUE_H_EXPL14               622
#define IDB_BLUE_H_EXPL15               623
#define IDB_BLUE_H_EXPL16               624
#define IDB_BLUE_H_EXPL17               625
#define IDB_BLUE_H_EXPL18               626
#define IDB_BLUE_H_EXPL19               627
#define IDB_BLUE_H_EXPL20               628
#define IDB_BLUE_H_EXPL21               629
#define IDB_BLUE_H_EXPL22               630
#define IDB_BLUE_H_EXPL23               631
#define IDB_BLUE_H_EXPL24               632
#define IDB_BLUE_H_EXPL25               633
#define IDB_BLUE_H_EXPL26               634
#define IDB_BLUE_H_EXPL27               635
#define IDB_BLUE_H_EXPL28               636
#define IDB_BLUE_H_EXPL29               637
#define IDB_BLUE_H_EXPL30               638
#define IDB_BITMAP10                    639
#define IDB_BITMAP11                    640
#define IDB_BITMAP12                    641
#define IDB_BITMAP13                    642
#define IDB_BITMAP14                    643
#define IDB_BITMAP15                    644
#define IDB_BITMAP16                    645
#define IDB_BITMAP17                    646
#define IDB_BITMAP18                    647
#define IDB_BITMAP19                    648
#define IDB_BITMAP20                    649
#define IDB_BITMAP21                    650
#define IDB_BITMAP22                    651
#define IDB_BITMAP23                    652
#define IDB_BITMAP24                    653
#define IDB_BITMAP25                    654
#define IDB_BITMAP26                    655
#define IDB_BITMAP27                    656
#define IDB_BITMAP28                    657
#define IDB_BITMAP29                    658
#define IDB_BITMAP30                    659
#define IDB_BITMAP31                    660
#define IDB_BITMAP32                    661
#define IDB_BITMAP33                    662
#define IDB_BITMAP34                    663
#define IDB_BITMAP35                    664
#define IDB_BITMAP36                    665
#define IDB_BITMAP37                    666
#define IDB_BITMAP38                    667
#define IDB_BITMAP39                    668
#define IDB_BLUE_V_EXPL1                669
#define IDB_BLUE_V_EXPL10               670
#define IDB_BLUE_V_EXPL11               671
#define IDB_BLUE_V_EXPL12               672
#define IDB_BLUE_V_EXPL13               673
#define IDB_BLUE_V_EXPL14               674
#define IDB_BLUE_V_EXPL15               675
#define IDB_BLUE_V_EXPL16               676
#define IDB_BLUE_V_EXPL17               677
#define IDB_BLUE_V_EXPL18               678
#define IDB_BLUE_V_EXPL19               679
#define IDB_BLUE_V_EXPL2                680
#define IDB_BLUE_V_EXPL20               681
#define IDB_BLUE_V_EXPL21               682
#define IDB_BLUE_V_EXPL22               683
#define IDB_BLUE_V_EXPL23               684
#define IDB_BLUE_V_EXPL24               685
#define IDB_BLUE_V_EXPL25               686
#define IDB_BLUE_V_EXPL26               687
#define IDB_BLUE_V_EXPL27               688
#define IDB_BLUE_V_EXPL28               689
#define IDB_BLUE_V_EXPL29               690
#define IDB_BLUE_V_EXPL3                691
#define IDB_BLUE_V_EXPL30               692
#define IDB_BLUE_V_EXPL4                693
#define IDB_BLUE_V_EXPL5                694
#define IDB_BLUE_V_EXPL6                695
#define IDB_BLUE_V_EXPL7                696
#define IDB_BLUE_V_EXPL8                697
#define IDB_BLUE_V_EXPL9                698
#define IDB_GREEN_H_EXPL1               699
#define IDB_GREEN_H_EXPL10              700
#define IDB_GREEN_H_EXPL11              701
#define IDB_GREEN_H_EXPL12              702
#define IDB_GREEN_H_EXPL13              703
#define IDB_GREEN_H_EXPL14              704
#define IDB_GREEN_H_EXPL15              705
#define IDB_GREEN_H_EXPL16              706
#define IDB_GREEN_H_EXPL17              707
#define IDB_GREEN_H_EXPL18              708
#define IDB_GREEN_H_EXPL19              709
#define IDB_GREEN_H_EXPL2               710
#define IDB_GREEN_H_EXPL20              711
#define IDB_GREEN_H_EXPL21              712
#define IDB_GREEN_H_EXPL22              713
#define IDB_GREEN_H_EXPL23              714
#define IDB_GREEN_H_EXPL24              715
#define IDB_GREEN_H_EXPL25              716
#define IDB_GREEN_H_EXPL26              717
#define IDB_GREEN_H_EXPL27              718
#define IDB_GREEN_H_EXPL28              719
#define IDB_GREEN_H_EXPL29              720
#define IDB_GREEN_H_EXPL3               721
#define IDB_GREEN_H_EXPL30              722
#define IDB_GREEN_H_EXPL4               723
#define IDB_GREEN_H_EXPL5               724
#define IDB_GREEN_H_EXPL6               725
#define IDB_GREEN_H_EXPL7               726
#define IDB_GREEN_H_EXPL8               727
#define IDB_GREEN_H_EXPL9               728
#define IDB_GREEN_V_EXPL1               729
#define IDB_GREEN_V_EXPL10              730
#define IDB_GREEN_V_EXPL11              731
#define IDB_GREEN_V_EXPL12              732
#define IDB_GREEN_V_EXPL13              733
#define IDB_GREEN_V_EXPL14              734
#define IDB_GREEN_V_EXPL15              735
#define IDB_GREEN_V_EXPL16              736
#define IDB_GREEN_V_EXPL17              737
#define IDB_GREEN_V_EXPL18              738
#define IDB_GREEN_V_EXPL19              739
#define IDB_GREEN_V_EXPL2               740
#define IDB_GREEN_V_EXPL20              741
#define IDB_GREEN_V_EXPL21              742
#define IDB_GREEN_V_EXPL22              743
#define IDB_GREEN_V_EXPL23              744
#define IDB_GREEN_V_EXPL24              745
#define IDB_GREEN_V_EXPL25              746
#define IDB_GREEN_V_EXPL26              747
#define IDB_GREEN_V_EXPL27              748
#define IDB_GREEN_V_EXPL28              749
#define IDB_GREEN_V_EXPL29              750
#define IDB_GREEN_V_EXPL3               751
#define IDB_GREEN_V_EXPL30              752
#define IDB_GREEN_V_EXPL4               753
#define IDB_GREEN_V_EXPL5               754
#define IDB_GREEN_V_EXPL6               755
#define IDB_GREEN_V_EXPL7               756
#define IDB_GREEN_V_EXPL8               757
#define IDB_GREEN_V_EXPL9               758
#define IDB_ORANGE_H_EXPL1              759
#define IDB_ORANGE_H_EXPL10             760
#define IDB_ORANGE_H_EXPL11             761
#define IDB_ORANGE_H_EXPL12             762
#define IDB_ORANGE_H_EXPL13             763
#define IDB_ORANGE_H_EXPL14             764
#define IDB_ORANGE_H_EXPL15             765
#define IDB_ORANGE_H_EXPL16             766
#define IDB_ORANGE_H_EXPL17             767
#define IDB_ORANGE_H_EXPL18             768
#define IDB_ORANGE_H_EXPL19             769
#define IDB_ORANGE_H_EXPL2              770
#define IDB_ORANGE_H_EXPL20             771
#define IDB_ORANGE_H_EXPL21             772
#define IDB_ORANGE_H_EXPL22             773
#define IDB_ORANGE_H_EXPL23             774
#define IDB_ORANGE_H_EXPL24             775
#define IDB_ORANGE_H_EXPL25             776
#define IDB_ORANGE_H_EXPL26             777
#define IDB_ORANGE_H_EXPL27             778
#define IDB_ORANGE_H_EXPL28             779
#define IDB_ORANGE_H_EXPL29             780
#define IDB_ORANGE_H_EXPL3              781
#define IDB_ORANGE_H_EXPL30             782
#define IDB_ORANGE_H_EXPL4              783
#define IDB_ORANGE_H_EXPL5              784
#define IDB_ORANGE_H_EXPL6              785
#define IDB_ORANGE_H_EXPL7              786
#define IDB_ORANGE_H_EXPL8              787
#define IDB_ORANGE_H_EXPL9              788
#define IDB_ORANGE_V_EXPL1              789
#define IDB_ORANGE_V_EXPL10             790
#define IDB_ORANGE_V_EXPL11             791
#define IDB_ORANGE_V_EXPL12             792
#define IDB_ORANGE_V_EXPL13             793
#define IDB_ORANGE_V_EXPL14             794
#define IDB_ORANGE_V_EXPL15             795
#define IDB_ORANGE_V_EXPL16             796
#define IDB_ORANGE_V_EXPL17             797
#define IDB_ORANGE_V_EXPL18             798
#define IDB_ORANGE_V_EXPL19             799
#define IDB_ORANGE_V_EXPL2              800
#define IDB_ORANGE_V_EXPL20             801
#define IDB_ORANGE_V_EXPL21             802
#define IDB_ORANGE_V_EXPL22             803
#define IDB_ORANGE_V_EXPL23             804
#define IDB_ORANGE_V_EXPL24             805
#define IDB_ORANGE_V_EXPL25             806
#define IDB_ORANGE_V_EXPL26             807
#define IDB_ORANGE_V_EXPL27             808
#define IDB_ORANGE_V_EXPL28             809
#define IDB_ORANGE_V_EXPL29             810
#define IDB_ORANGE_V_EXPL3              811
#define IDB_ORANGE_V_EXPL30             812
#define IDB_ORANGE_V_EXPL4              813
#define IDB_ORANGE_V_EXPL5              814
#define IDB_ORANGE_V_EXPL6              815
#define IDB_ORANGE_V_EXPL7              816
#define IDB_ORANGE_V_EXPL8              817
#define IDB_ORANGE_V_EXPL9              818
#define IDB_PURPLE_H_EXPL1              819
#define IDB_PURPLE_H_EXPL10             820
#define IDB_PURPLE_H_EXPL11             821
#define IDB_PURPLE_H_EXPL12             822
#define IDB_PURPLE_H_EXPL13             823
#define IDB_PURPLE_H_EXPL14             824
#define IDB_PURPLE_H_EXPL15             825
#define IDB_PURPLE_H_EXPL16             826
#define IDB_PURPLE_H_EXPL17             827
#define IDB_PURPLE_H_EXPL18             828
#define IDB_PURPLE_H_EXPL19             829
#define IDB_PURPLE_H_EXPL2              830
#define IDB_PURPLE_H_EXPL20             831
#define IDB_PURPLE_H_EXPL21             832
#define IDB_PURPLE_H_EXPL22             833
#define IDB_PURPLE_H_EXPL23             834
#define IDB_PURPLE_H_EXPL24             835
#define IDB_PURPLE_H_EXPL25             836
#define IDB_PURPLE_H_EXPL26             837
#define IDB_PURPLE_H_EXPL27             838
#define IDB_PURPLE_H_EXPL28             839
#define IDB_PURPLE_H_EXPL29             840
#define IDB_PURPLE_H_EXPL3              841
#define IDB_PURPLE_H_EXPL30             842
#define IDB_PURPLE_H_EXPL4              843
#define IDB_PURPLE_H_EXPL5              844
#define IDB_PURPLE_H_EXPL6              845
#define IDB_PURPLE_H_EXPL7              846
#define IDB_PURPLE_H_EXPL8              847
#define IDB_PURPLE_H_EXPL9              848
#define IDB_PURPLE_V_EXPL1              849
#define IDB_PURPLE_V_EXPL10             850
#define IDB_PURPLE_V_EXPL11             851
#define IDB_PURPLE_V_EXPL12             852
#define IDB_PURPLE_V_EXPL13             853
#define IDB_PURPLE_V_EXPL14             854
#define IDB_PURPLE_V_EXPL15             855
#define IDB_PURPLE_V_EXPL16             856
#define IDB_PURPLE_V_EXPL17             857
#define IDB_PURPLE_V_EXPL18             858
#define IDB_PURPLE_V_EXPL19             859
#define IDB_PURPLE_V_EXPL2              860
#define IDB_PURPLE_V_EXPL20             861
#define IDB_PURPLE_V_EXPL21             862
#define IDB_PURPLE_V_EXPL22             863
#define IDB_PURPLE_V_EXPL23             864
#define IDB_PURPLE_V_EXPL24             865
#define IDB_PURPLE_V_EXPL25             866
#define IDB_PURPLE_V_EXPL26             867
#define IDB_PURPLE_V_EXPL27             868
#define IDB_PURPLE_V_EXPL28             869
#define IDB_PURPLE_V_EXPL29             870
#define IDB_PURPLE_V_EXPL3              871
#define IDB_PURPLE_V_EXPL30             872
#define IDB_PURPLE_V_EXPL4              873
#define IDB_PURPLE_V_EXPL5              874
#define IDB_PURPLE_V_EXPL6              875
#define IDB_PURPLE_V_EXPL7              876
#define IDB_PURPLE_V_EXPL8              877
#define IDB_PURPLE_V_EXPL9              878
#define IDB_RED_H_EXPL1                 879
#define IDB_RED_H_EXPL10                880
#define IDB_RED_H_EXPL11                881
#define IDB_RED_H_EXPL12                882
#define IDB_RED_H_EXPL13                883
#define IDB_RED_H_EXPL14                884
#define IDB_RED_H_EXPL15                885
#define IDB_RED_H_EXPL16                886
#define IDB_RED_H_EXPL17                887
#define IDB_RED_H_EXPL18                888
#define IDB_RED_H_EXPL19                889
#define IDB_RED_H_EXPL2                 890
#define IDB_RED_H_EXPL20                891
#define IDB_RED_H_EXPL21                892
#define IDB_RED_H_EXPL22                893
#define IDB_RED_H_EXPL23                894
#define IDB_RED_H_EXPL24                895
#define IDB_RED_H_EXPL25                896
#define IDB_RED_H_EXPL26                897
#define IDB_RED_H_EXPL27                898
#define IDB_RED_H_EXPL28                899
#define IDB_RED_H_EXPL29                900
#define IDB_RED_H_EXPL3                 901
#define IDB_RED_H_EXPL30                902
#define IDB_RED_H_EXPL4                 903
#define IDB_RED_H_EXPL5                 904
#define IDB_RED_H_EXPL6                 905
#define IDB_RED_H_EXPL7                 906
#define IDB_RED_H_EXPL8                 907
#define IDB_RED_H_EXPL9                 908
#define IDB_RED_V_EXPL1                 909
#define IDB_RED_V_EXPL10                910
#define IDB_RED_V_EXPL11                911
#define IDB_RED_V_EXPL12                912
#define IDB_RED_V_EXPL13                913
#define IDB_RED_V_EXPL14                914
#define IDB_RED_V_EXPL15                915
#define IDB_RED_V_EXPL16                916
#define IDB_RED_V_EXPL17                917
#define IDB_RED_V_EXPL18                918
#define IDB_RED_V_EXPL19                919
#define IDB_RED_V_EXPL2                 920
#define IDB_RED_V_EXPL20                921
#define IDB_RED_V_EXPL21                922
#define IDB_RED_V_EXPL22                923
#define IDB_RED_V_EXPL23                924
#define IDB_RED_V_EXPL24                925
#define IDB_RED_V_EXPL25                926
#define IDB_RED_V_EXPL26                927
#define IDB_RED_V_EXPL27                928
#define IDB_RED_V_EXPL28                929
#define IDB_RED_V_EXPL29                930
#define IDB_RED_V_EXPL3                 931
#define IDB_RED_V_EXPL30                932
#define IDB_RED_V_EXPL4                 933
#define IDB_RED_V_EXPL5                 934
#define IDB_RED_V_EXPL6                 935
#define IDB_RED_V_EXPL7                 936
#define IDB_RED_V_EXPL8                 937
#define IDB_RED_V_EXPL9                 938
#define IDB_YELLOW_H_EXPL1              939
#define IDB_YELLOW_H_EXPL10             940
#define IDB_YELLOW_H_EXPL11             941
#define IDB_YELLOW_H_EXPL12             942
#define IDB_YELLOW_H_EXPL13             943
#define IDB_YELLOW_H_EXPL14             944
#define IDB_YELLOW_H_EXPL15             945
#define IDB_YELLOW_H_EXPL16             946
#define IDB_YELLOW_H_EXPL17             947
#define IDB_YELLOW_H_EXPL18             948
#define IDB_YELLOW_H_EXPL19             949
#define IDB_YELLOW_H_EXPL2              950
#define IDB_YELLOW_H_EXPL20             951
#define IDB_YELLOW_H_EXPL21             952
#define IDB_YELLOW_H_EXPL22             953
#define IDB_YELLOW_H_EXPL23             954
#define IDB_YELLOW_H_EXPL24             955
#define IDB_YELLOW_H_EXPL25             956
#define IDB_YELLOW_H_EXPL26             957
#define IDB_YELLOW_H_EXPL27             958
#define IDB_YELLOW_H_EXPL28             959
#define IDB_YELLOW_H_EXPL29             960
#define IDB_YELLOW_H_EXPL3              961
#define IDB_YELLOW_H_EXPL30             962
#define IDB_YELLOW_H_EXPL4              963
#define IDB_YELLOW_H_EXPL5              964
#define IDB_YELLOW_H_EXPL6              965
#define IDB_YELLOW_H_EXPL7              966
#define IDB_YELLOW_H_EXPL8              967
#define IDB_YELLOW_H_EXPL9              968
#define IDB_YELLOW_V_EXPL1              969
#define IDB_YELLOW_V_EXPL10             970
#define IDB_YELLOW_V_EXPL11             971
#define IDB_YELLOW_V_EXPL12             972
#define IDB_YELLOW_V_EXPL13             973
#define IDB_YELLOW_V_EXPL14             974
#define IDB_YELLOW_V_EXPL15             975
#define IDB_YELLOW_V_EXPL16             976
#define IDB_YELLOW_V_EXPL17             977
#define IDB_YELLOW_V_EXPL18             978
#define IDB_YELLOW_V_EXPL19             979
#define IDB_YELLOW_V_EXPL2              980
#define IDB_YELLOW_V_EXPL20             981
#define IDB_YELLOW_V_EXPL21             982
#define IDB_YELLOW_V_EXPL22             983
#define IDB_YELLOW_V_EXPL23             984
#define IDB_YELLOW_V_EXPL24             985
#define IDB_YELLOW_V_EXPL25             986
#define IDB_YELLOW_V_EXPL26             987
#define IDB_YELLOW_V_EXPL27             988
#define IDB_YELLOW_V_EXPL28             989
#define IDB_YELLOW_V_EXPL29             990
#define IDB_YELLOW_V_EXPL3              991
#define IDB_YELLOW_V_EXPL30             992
#define IDB_YELLOW_V_EXPL4              993
#define IDB_YELLOW_V_EXPL5              994
#define IDB_YELLOW_V_EXPL6              995
#define IDB_YELLOW_V_EXPL7              996
#define IDB_YELLOW_V_EXPL8              997
#define IDB_YELLOW_V_EXPL9              998
#define IDB_BITMAP40                    999
#define IDB_BLUE_SHAT1                  999
#define IDB_BLUE_SHAT10                 1000
#define IDC_README                      1001
#define IDB_BLUE_SHAT11                 1001
#define IDB_BLUE_SHAT12                 1002
#define IDB_BLUE_SHAT13                 1003
#define IDB_BLUE_SHAT14                 1004
#define IDB_BLUE_SHAT15                 1005
#define IDB_BLUE_SHAT2                  1006
#define IDB_BLUE_SHAT3                  1007
#define IDB_BLUE_SHAT4                  1008
#define IDB_BLUE_SHAT5                  1009
#define IDB_BLUE_SHAT6                  1010
#define IDB_BLUE_SHAT7                  1011
#define IDB_BLUE_SHAT8                  1012
#define IDB_BLUE_SHAT9                  1013
#define IDB_GREEN_SHAT1                 1014
#define IDB_GREEN_SHAT10                1015
#define IDB_GREEN_SHAT11                1016
#define IDB_GREEN_SHAT12                1017
#define IDB_GREEN_SHAT13                1018
#define IDB_GREEN_SHAT14                1019
#define IDB_GREEN_SHAT15                1020
#define IDB_GREEN_SHAT2                 1021
#define IDB_GREEN_SHAT3                 1022
#define IDB_GREEN_SHAT4                 1023
#define IDB_GREEN_SHAT5                 1024
#define IDB_GREEN_SHAT6                 1025
#define IDB_GREEN_SHAT7                 1026
#define IDB_GREEN_SHAT8                 1027
#define IDB_GREEN_SHAT9                 1028
#define IDB_ORANGE_SHAT1                1029
#define IDB_ORANGE_SHAT10               1030
#define IDB_ORANGE_SHAT11               1031
#define IDB_ORANGE_SHAT12               1032
#define IDB_ORANGE_SHAT13               1033
#define IDB_ORANGE_SHAT14               1034
#define IDB_ORANGE_SHAT15               1035
#define IDB_ORANGE_SHAT2                1036
#define IDB_ORANGE_SHAT3                1037
#define IDB_ORANGE_SHAT4                1038
#define IDB_ORANGE_SHAT5                1039
#define IDB_ORANGE_SHAT6                1040
#define IDB_ORANGE_SHAT7                1041
#define IDB_ORANGE_SHAT8                1042
#define IDB_ORANGE_SHAT9                1043
#define IDB_PURPLE_SHAT1                1044
#define IDB_PURPLE_SHAT10               1045
#define IDB_PURPLE_SHAT11               1046
#define IDB_PURPLE_SHAT12               1047
#define IDB_PURPLE_SHAT13               1048
#define IDB_PURPLE_SHAT14               1049
#define IDB_PURPLE_SHAT15               1050
#define IDB_PURPLE_SHAT2                1051
#define IDB_PURPLE_SHAT3                1052
#define IDB_PURPLE_SHAT4                1053
#define IDB_PURPLE_SHAT5                1054
#define IDB_PURPLE_SHAT6                1055
#define IDB_PURPLE_SHAT7                1056
#define IDB_PURPLE_SHAT8                1057
#define IDB_PURPLE_SHAT9                1058
#define IDB_RED_SHAT1                   1059
#define IDB_RED_SHAT10                  1060
#define IDB_RED_SHAT11                  1061
#define IDB_RED_SHAT12                  1062
#define IDB_RED_SHAT13                  1063
#define IDB_RED_SHAT14                  1064
#define IDB_RED_SHAT15                  1065
#define IDB_RED_SHAT2                   1066
#define IDB_RED_SHAT3                   1067
#define IDB_RED_SHAT4                   1068
#define IDB_RED_SHAT5                   1069
#define IDB_RED_SHAT6                   1070
#define IDB_RED_SHAT7                   1071
#define IDB_RED_SHAT8                   1072
#define IDB_RED_SHAT9                   1073
#define IDB_YELLOW_SHAT1                1074
#define IDB_YELLOW_SHAT10               1075
#define IDB_YELLOW_SHAT11               1076
#define IDB_YELLOW_SHAT12               1077
#define IDB_YELLOW_SHAT13               1078
#define IDB_YELLOW_SHAT14               1079
#define IDB_YELLOW_SHAT15               1080
#define IDB_YELLOW_SHAT2                1081
#define IDB_YELLOW_SHAT3                1082
#define IDB_YELLOW_SHAT4                1083
#define IDB_YELLOW_SHAT5                1084
#define IDB_YELLOW_SHAT6                1085
#define IDB_YELLOW_SHAT7                1086
#define IDB_YELLOW_SHAT8                1087
#define IDB_YELLOW_SHAT9                1088
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1089
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
