//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MONSTER                     157
#define IDB_BLUE                        163
#define IDB_BITMAP3                     164
#define IDB_RED                         164
#define IDB_LOGOCANDY1                  165
#define IDB_LOGOCANDY2                  166
#define IDB_LOGOCANDY3                  167
#define IDB_LOGOCANDY4                  168
#define IDB_LOGOCANDY5                  169
#define IDB_LOGOCANDY6                  170
#define IDB_LOGOCANDY7                  171
#define IDB_LOGOCANDY8                  172
#define IDB_LOGOCANDY9                  173
#define IDB_LOGOCANDY10                 174
#define IDB_LOGOCANDY11                 175
#define IDB_LOGOCANDY12                 176
#define IDB_LOGOCANDY13                 177
#define IDB_LOGOCANDY14                 178
#define IDB_LOGOCANDY15                 179
#define IDB_LOGOCANDY16                 180
#define IDB_LOGOCANDY17                 181
#define IDB_LOGOCANDY18                 182
#define IDB_LOGOCANDY19                 183
#define IDB_LOGOCANDY20                 184
#define IDB_LOGOCANDY21                 185
#define IDB_LOGOCANDY22                 186
#define IDB_LOGOCANDY23                 187
#define IDB_LOGOTIFFY0                  189
#define IDB_LOGOTIFFY1                  190
#define IDB_LOGOTIFFY2                  191
#define IDB_LOGOTIFFY3                  192
#define IDB_LOGOTIFFY4                  193
#define IDB_LOGOTIFFY5                  194
#define IDB_LOGOTIFFY6                  195
#define IDB_LOGOTIFFY7                  196
#define IDB_LOGOTIFFY8                  197
#define IDB_LOGOTIFFY9                  198
#define IDB_LOGOTOFFEE46                199
#define IDB_LOGOTOFFEE1                 199
#define IDB_LOGOTOFFEE2                 200
#define IDB_LOGOTOFFEE3                 201
#define IDB_LOGOTOFFEE4                 202
#define IDB_LOGOTOFFEE5                 203
#define IDB_LOGOTOFFEE6                 204
#define IDB_PLAYBUTTON_1                206
#define IDB_PLAYBUTTON_2                209
#define IDB_PLAYBUTTON_3                210
#define IDB_PLAYBUTTON_4                211
#define IDB_PLAYBUTTON_5                212
#define IDB_PLAYBUTTON_6                213
#define IDB_PLAYBUTTON_7                214
#define IDB_PLAYBUTTON_8                215
#define IDB_PLAYBUTTON_9                216
#define IDB_PLAYBUTTON_10               217
#define IDB_PLAYBUTTON_11               218
#define IDB_PLAYBUTTON_12               219
#define IDB_BITMAP4                     221
#define IDB_BITMAP5                     223
#define IDB_STAGE_BUTTON_BLUE           224
#define IDB_ORANGE_C                    226
#define IDB_STAGE_BUTTON_GREEN          226
#define IDB_PURPLE_C                    227
#define IDB_STAGE_BUTTON_GREY           227
#define IDB_STAGE_BUTTON_RED            228
#define IDB_BITMAP6                     229
#define IDB_YELLOW_C                    229
#define IDB_STAGE_BUTTON_YELLOW         229
#define IDB_SUPER                       232
#define IDB_SUPER_C                     234
#define IDB_BLUE_C                      236
#define IDB_RED_C                       237
#define IDB_GREEN_C                     239
#define IDB_BLUE_CLICKED                240
#define IDB_GREEN_CLICKED               241
#define IDB_ORANGE_CLICKED              242
#define IDB_PURPLE_CLICKED              244
#define IDB_RED_CLICKED                 245
#define IDB_YELLOW_CLICKED              246
#define IDB_BLUE_HOR                    247
#define IDB_GREEN_HOR                   248
#define IDB_ORANGE_HOR                  249
#define IDB_PURPLE_HOR                  250
#define IDB_RED_HOR                     252
#define IDB_YELLOW_HOR                  253
#define IDB_BLUE_HOR_C                  254
#define IDB_GREEN_HOR_C                 255
#define IDB_ORANGE_HOR_C                256
#define IDB_PURPLE_HOR_C                257
#define IDB_RED_HOR_C                   259
#define IDB_YELLOW_HOR_C                260
#define IDB_BLUE_VER                    261
#define IDB_GREEN_VER                   262
#define IDB_ORANGE_VER                  263
#define IDB_PURPLE_VER                  264
#define IDB_RED_VER                     265
#define IDB_YELLOW_VER                  266
#define IDB_BLUE_VER_C                  267
#define IDB_GREEN_VER_C                 268
#define IDB_ORANGE_VER_C                269
#define IDB_PURPLE_VER_C                271
#define IDB_RED_VER_C                   272
#define IDB_YELLOW_VER_C                273
#define IDB_ORANGE_PACK                 278
#define IDB_BLUE_PACK                   279
#define IDB_GREEN_PACK                  280
#define IDB_PURPLE_PACK                 281
#define IDB_RED_PACK                    282
#define IDB_YELLOW_PACK                 283
#define IDB_BLUE_PACK_C                 284
#define IDB_GREEN_PACK_C                285
#define IDB_ORANGE_PACK__C              286
#define IDB_ORANGE_PACK_C               286
#define IDB_PURPLE_PACK_C               287
#define IDB_RED_PACK_C                  288
#define IDB_YELLOW_PACK_C               289
#define IDB_BLACKBAR                    290
#define IDB_0                           293
#define IDB_1                           295
#define IDB_2                           296
#define IDB_3                           335
#define IDB_4                           336
#define IDB_5                           337
#define IDB_8                           343
#define IDB_9                           345
#define IDB1_0                          346
#define IDB1_1                          347
#define IDB1_2                          348
#define IDB1_3                          349
#define IDB1_4                          350
#define IDB1_5                          351
#define IDB1_6                          352
#define IDB1_7                          354
#define IDB1_8                          355
#define IDB1_9                          357
#define IDB2_0                          358
#define IDB2_1                          359
#define IDB2_2                          360
#define IDB2_3                          361
#define IDB2_4                          362
#define IDB2_5                          363
#define IDB2_6                          364
#define IDB2_7                          365
#define IDB2_8                          366
#define IDB2_9                          368
#define IDB3_0                          369
#define IDB3_1                          370
#define IDB3_2                          371
#define IDB3_3                          372
#define IDB3_4                          373
#define IDB3_5                          374
#define IDB3_6                          375
#define IDB3_7                          376
#define IDB3_8                          377
#define IDB_BITMAP7                     378
#define IDB3_9                          378
#define IDB_CONTAINER                   381
#define IDB_INGAME_LOADING              382
#define IDB_6                           385
#define IDB_7                           386
#define IDB_NEXTBTN_0                   387
#define IDB_NEXTBTN_1                   388
#define IDB_NEXTBTN_2                   389
#define IDB_NEXTBTN_3                   390
#define IDB_NEXTBTN_4                   391
#define IDB_NEXTBTN_5                   392
#define IDB_NEXTBTN_6                   393
#define IDB_NEXTBTN_7                   395
#define IDB_NEXTBTN_8                   396
#define IDB_NEXTBTN_9                   397
#define IDB_RETRYBTN_0                  398
#define IDB_RETRYBTN_1                  399
#define IDB_RETRYBTN_2                  400
#define IDB_RETRYBTN_3                  401
#define IDB_RETRYBTN_4                  403
#define IDB_RETRYBTN_5                  404
#define IDB_RETRYBTN_6                  405
#define IDB_RETRYBTN_7                  407
#define IDB_RETRYBTN_8                  409
#define IDB_BITMAP8                     410
#define IDB_RETRYBTN_9                  410
#define IDB_BLUE_EXPL1                  411
#define IDB_BLUE_EXPL2                  413
#define IDB_BLUE_EXPL3                  414
#define IDB_BLUE_EXPL4                  415
#define IDB_BLUE_EXPL5                  417
#define IDB_BLUE_EXPL6                  418
#define IDB_BLUE_EXPL7                  419
#define IDB_BLUE_EXPL8                  420
#define IDB_BLUE_EXPL9                  421
#define IDB_BLUE_EXPL10                 422
#define IDB_GREEN_EXPL1                 559
#define IDB_GREEN_EXPL2                 560
#define IDB_GREEN_EXPL3                 561
#define IDB_GREEN_EXPL4                 562
#define IDB_GREEN_EXPL5                 563
#define IDB_GREEN_EXPL6                 564
#define IDB_GREEN_EXPL7                 565
#define IDB_GREEN_EXPL8                 566
#define IDB_GREEN_EXPL9                 567
#define IDB_GREEN_EXPL10                568
#define IDB_ORANGE_EXPL1                569
#define IDB_ORANGE_EXPL2                570
#define IDB_ORANGE_EXPL3                571
#define IDB_ORANGE_EXPL4                572
#define IDB_ORANGE_EXPL5                573
#define IDB_ORANGE_EXPL6                574
#define IDB_ORANGE_EXPL7                575
#define IDB_ORANGE_EXPL8                576
#define IDB_ORANGE_EXPL9                577
#define IDB_ORANGE_EXPL10               578
#define IDB_PURPLE_EXPL1                579
#define IDB_PURPLE_EXPL2                580
#define IDB_PURPLE_EXPL3                581
#define IDB_PURPLE_EXPL4                582
#define IDB_PURPLE_EXPL5                583
#define IDB_PURPLE_EXPL6                584
#define IDB_PURPLE_EXPL7                585
#define IDB_PURPLE_EXPL8                586
#define IDB_PURPLE_EXPL9                587
#define IDB_PURPLE_EXPL10               588
#define IDB_RED_EXPL1                   589
#define IDB_RED_EXPL2                   590
#define IDB_RED_EXPL3                   591
#define IDB_RED_EXPL4                   592
#define IDB_RED_EXPL5                   593
#define IDB_RED_EXPL6                   594
#define IDB_RED_EXPL7                   595
#define IDB_RED_EXPL8                   596
#define IDB_RED_EXPL9                   597
#define IDB_RED_EXPL10                  598
#define IDB_BITMAP9                     599
#define IDB_YELLOW_EXPL1                599
#define IDB_YELLOW_EXPL2                600
#define IDB_YELLOW_EXPL3                601
#define IDB_YELLOW_EXPL4                602
#define IDB_YELLOW_EXPL5                603
#define IDB_YELLOW_EXPL6                604
#define IDB_YELLOW_EXPL7                605
#define IDB_YELLOW_EXPL8                606
#define IDB_YELLOW_EXPL9                607
#define IDB_YELLOW_EXPL10               608
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        609
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
